name: Build UnrealScript (Linux)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build container image
        # Gpu somewhat needed
        run: podman build --device /dev/dri -t outlast-unrealscript -f CI/Containerfile_unrealscript .

      - name: Extract binary from image
        run: |
          id=$(podman create outlast-unrealscript)
          podman cp "$id":/build/Outlast-Level-Editor/UDKGame/Script/Multiplayer.u ./Multiplayer.u
          podman rm "$id"

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Launcher
          path: Multiplayer.u
          archive: false
